import type { AbilityDefinition } from './types';

// ---------------------------------------------------------------------------
// Active abilities. Each monster gets exactly one for the MVP. Cooldowns are
// tuned so an ability fires a handful of times per wave, not every attack.
// ---------------------------------------------------------------------------

export const ABILITIES: Record<string, AbilityDefinition> = {
  gearBarrage: {
    id: 'gearBarrage',
    name: 'Gear Barrage',
    description: 'Fires a volley of spinning cogs at the current target.',
    kind: 'barrage',
    cooldownMs: 6000,
    power: 1.8,
  },
  cinderBurst: {
    id: 'cinderBurst',
    name: 'Cinder Burst',
    description: 'Vents its boiler in a scalding blast around the target.',
    kind: 'aoe_damage',
    cooldownMs: 7000,
    power: 2.2,
    radius: 70,
  },
  arcChain: {
    id: 'arcChain',
    name: 'Arc Chain',
    description: 'Discharges copper coils, arcing between nearby foes.',
    kind: 'chain',
    cooldownMs: 5500,
    power: 1.3,
    chainCount: 2,
    radius: 90,
  },
  pistonSlam: {
    id: 'pistonSlam',
    name: 'Piston Slam',
    description: 'Drives its piston legs into the ground, shaking the area.',
    kind: 'aoe_damage',
    cooldownMs: 8000,
    power: 2.6,
    radius: 60,
  },
  condensingMist: {
    id: 'condensingMist',
    name: 'Condensing Mist',
    description: 'Sprays pressurized vapor that chills and slows foes.',
    kind: 'slow_field',
    cooldownMs: 7500,
    power: 0.45,
    radius: 85,
    durationMs: 2200,
  },
  sporeVent: {
    id: 'sporeVent',
    name: 'Spore Vent',
    description: 'Releases chlorophyll-lit spores that poison the area.',
    kind: 'dot_area',
    cooldownMs: 8000,
    power: 0.7,
    radius: 75,
    durationMs: 3000,
  },
  cycloneBarrage: {
    id: 'cycloneBarrage',
    name: 'Cyclone Barrage',
    description: 'Spins its propeller into a rapid multi-hit gust.',
    kind: 'barrage',
    cooldownMs: 5000,
    power: 1.6,
  },
  cryoVent: {
    id: 'cryoVent',
    name: 'Cryo Vent',
    description: 'Vents supercooled steam, freezing the ground and foes.',
    kind: 'slow_field',
    cooldownMs: 8500,
    power: 0.6,
    radius: 80,
    durationMs: 2800,
  },
  umbralChain: {
    id: 'umbralChain',
    name: 'Umbral Chain',
    description: 'Ticking brass cogs unspool into whip-fast shadow lashes.',
    kind: 'chain',
    cooldownMs: 6500,
    power: 1.6,
    chainCount: 3,
    radius: 100,
  },
  aetherStorm: {
    id: 'aetherStorm',
    name: 'Aether Storm',
    description: 'Unleashes a legendary lightning-glass tempest.',
    kind: 'aoe_damage',
    cooldownMs: 9000,
    power: 3.2,
    radius: 110,
  },
};
